# Generated by Django 4.0.5 on 2022-06-20 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=175)),
                ('school_or_college', models.CharField(max_length=255)),
                ('certificate', models.BooleanField()),
                ('description', models.TextField()),
                ('finished_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
